"""Render CVPR ablation tables from the audited local result snapshot.

Run with --check to check reproducibility without changing files.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'results/competitor_ablation/verified_metrics.json'
NAMES = {'core': 'Core', 'ext2': 'Extended'}
ROW = r' \\' + '\n'


def table(spec, header, rows, caption, label, wide=False):
    env = 'table*' if wide else 'table'
    return ('% Generated by scripts/render_competitor_ablation.py; do not edit numbers.\n'
            + f'\\begin{{{env}}}[t]\n    \\centering\n    \\footnotesize\n'
            + '    \\setlength{\\tabcolsep}{4pt}\n'
            + f'    \\begin{{tabular}}{{{spec}}}\n        \\toprule\n        '
            + header + ROW + '        \\midrule\n'
            + ''.join('        ' + row + ROW for row in rows)
            + '        \\bottomrule\n    \\end{tabular}\n'
            + f'    \\caption{{{caption}}}\n    \\label{{{label}}}\n'
            + f'\\end{{{env}}}\n')


def interval(row, key='image_bootstrap_95'):
    lo, hi = row[key]['interval']
    return f'$[{100*lo:+.3f},{100*hi:+.3f}]$'


def auc_sd(row, bold=False):
    mean = f"{row['macro_auc']:.4f}"
    if bold:
        mean = r'\mathbf{' + mean + '}'
    return f"${mean}\\pm{row['seed_macro_auc_sd']:.4f}$"


def render(data):
    datasets = data['datasets']

    def block(dataset, scenario, layer=18):
        return datasets[dataset]['layers'][str(layer)]['scenarios'][scenario]

    rows = []
    for dataset in NAMES:
        b = block(dataset, 'B')
        for k in (2, 4, 8):
            row = b['variants'][f'B_K{k}']
            rows.append(' & '.join([f"{NAMES[dataset]} ({len(b['classes'])})", str(k),
                                    auc_sd(row, bold=k == 8), (r'\textbf{' + f"{row['macro_ap']:.4f}" + '}'
                                    if k == 8 else f"{row['macro_ap']:.4f}")]))
    files = {'competitor_budget.tex': table('lrrr',
        r'Menu (categories) & $K$ & Macro AUC $\uparrow$ & AP $\uparrow$', rows,
        r'\textbf{Competitor count at a fixed budget.} Qwen2.5-VL-3B-Instruct, '
        r'L18, 32 fitting records per category. AUC is mean $\pm$ sample SD '
        r'over 20 fitting seeds; AP is the mean macro AP. All values use the '
        r'0--1 scale. Each menu uses a common eligible cohort across $K$. '
        r'Seed SD measures fitting variability and is distinct from the paired '
        r'image-bootstrap intervals reported in the text.', 'tab:competitor_budget')}
    rows = []
    for dataset in NAMES:
        a = block(dataset, 'A')
        for v in ('A0', 'A1', 'A2'):
            r = a['variants'][v]
            rows.append(' & '.join([NAMES[dataset], v, f"{r['macro_auc']:.4f}", f"{r['macro_ap']:.4f}"]))
    files['competitor_weighting.tex'] = table('llrr',
        r'Menu & Weights & AUC $\uparrow$ & AP $\uparrow$', rows,
        r'\textbf{All-record weighting at L18.} Core uses 10 categories and '
        r'Extended uses 76. A0 weights records equally, A1 weights observed '
        r'competitors equally, and A2 uses intermediate count weighting '
        r'($\gamma=1,0,1/2$ in \cref{eq:competitor_weighting}). '
        r'Pair means retain their magnitudes; only the final direction is '
        r'normalized. Metrics use the 0--1 scale.', 'tab:competitor_weighting')
    rows = []
    for scenario, comparison, name in [('A', 'A1-A0', 'A1$-$A0'),
                                       ('B', 'B_K8-B_K2', '$K=8$ minus $K=2$')]:
        b = block('ext2', scenario); r = b['comparisons'][comparison]
        rows.append(' & '.join([name, str(len(b['classes'])),
                               f"${100*r['delta_macro_auc']:+.3f}$", interval(r),
                               interval(r, 'bonferroni_simultaneous_97_5')]))
    files['competitor_primary.tex'] = table('lrrrr',
        r'Comparison & Categories & $\Delta$ (pp) & 95\% CI (pp) & 97.5\% CI (pp)', rows,
        r'\textbf{Primary comparisons on Extended at L18.} The two '
        r'Bonferroni-adjusted 97.5\% intervals give at least 95\% simultaneous '
        r'coverage for these comparisons. All differences and endpoints are '
        r'absolute AUC percentage points. The 2,000 paired bootstrap draws '
        r'condition on the saved contrasts and fixed fitting seeds.', 'tab:competitor_primary', True)
    rows = []
    for layer in (1, 9, 18, 27, 35):
        values = [str(layer)]
        for dataset in NAMES:
            r = block(dataset, 'A', layer)['comparisons']['A1-A0']
            values.extend([f"${100*r['delta_macro_auc']:+.3f}$", interval(r)])
        rows.append(' & '.join(values))
    files['competitor_layers.tex'] = table('rrrrr',
        r'Layer & Core $\Delta$ & Core 95\% CI & Extended $\Delta$ & Extended 95\% CI', rows,
        r'\textbf{A1 minus A0 across depth.} Differences and intervals use '
        r'AUC percentage points. Cohorts are the full 10-category Core and '
        r'76-category Extended menus. L18 is primary for Extended; the other '
        r'comparisons are secondary, with unadjusted 95\% intervals.', 'tab:competitor_layers', True)
    rows = []
    for layer in (9, 18):
        for dataset in NAMES:
            b = block(dataset, 'B', layer)
            r = b['comparisons']['B_K8-B_K2']
            rows.append(' & '.join([NAMES[dataset], str(layer),
                *[f"{b['variants'][f'B_K{k}']['macro_auc']:.4f}" for k in (2, 4, 8)],
                f"${100*r['delta_macro_auc']:+.3f}$", interval(r)]))
    files['competitor_layers.tex'] += '\n' + table('lrrrrrr',
        r'Menu & Layer & $K=2$ & $K=4$ & $K=8$ & $\Delta_{8-2}$ (pp) & 95\% CI (pp)', rows,
        r'\textbf{Competitor count at L9 and L18.} Mean macro AUC on the same '
        r'7 Core or 64 Extended categories across $K$ and layers, using 20 '
        r'fits and 32 records per category. AUCs use the 0--1 scale; paired '
        r'differences use percentage points. Intervals are marginal 95\% '
        r'image-bootstrap intervals.', 'tab:competitor_budget_layers', True)
    rows = []
    b = block('ext2', 'B_area')
    for setting, prefix in [('Natural', 'B'), ('Controlled', 'B_area')]:
        for k in (2, 4, 8):
            r = b['variants'][f'{prefix}_K{k}']
            rows.append(' & '.join([setting, str(k), auc_sd(r), f"{r['macro_ap']:.4f}"]))
    files['competitor_area.tex'] = table('lrrr',
        r'Area setting & $K$ & AUC $\uparrow$ & AP $\uparrow$', rows,
        r'\textbf{Area control on Extended at L18.} Both settings use the '
        r'same 54 eligible categories, 32 records per category, and 20 fits. '
        r'Controlled fits use per-category area-level counts $(8,8,16)$. '
        r'AUC is mean $\pm$ seed SD; AP is a mean, both on the 0--1 scale. '
        r'Core has no eligible category for this control.', 'tab:competitor_area')
    rows = []
    for dataset in NAMES:
        for setting, scenario in [('Natural', 'C'), ('Controlled', 'C_area')]:
            b = block(dataset, scenario)
            for family in ('same', 'mixed', 'cross'):
                r = b['variants'][f'{scenario}_{family}']
                rows.append(' & '.join([NAMES[dataset], setting, family.capitalize(), auc_sd(r), f"{r['macro_ap']:.4f}"]))
    files['competitor_family.tex'] = table('lllrr',
        r'Menu & Area setting & Competitors & AUC $\uparrow$ & AP $\uparrow$', rows,
        r'\textbf{Competitor-family selection at L18.} All fits use two '
        r'competitors and 32 records per category. Core uses three categories; '
        r'Extended uses 21, with the same cohorts under area control. AUC is '
        r'mean $\pm$ seed SD over 20 fits; AP is the mean macro AP (0--1 '
        r'scale). These comparisons are secondary.', 'tab:competitor_family', True)
    rows = []
    for dataset in NAMES:
        for setting, scenario in [('Natural', 'C'), ('Controlled', 'C_area')]:
            r = block(dataset, scenario)['comparisons'][f'{scenario}_cross-{scenario}_same']
            rows.append(' & '.join([NAMES[dataset], setting,
                                    f"${100*r['delta_macro_auc']:+.3f}$", interval(r)]))
    files['competitor_family.tex'] += '\n' + table('llrr',
        r'Menu & Area & $\Delta$ (pp) & 95\% CI (pp)', rows,
        r'\textbf{Cross-family minus same-family AUC at L18.} Percentage '
        r'points with unadjusted 95\% paired image-bootstrap intervals. '
        r'Intervals condition on the saved contrasts and fixed 20 fits.', 'tab:competitor_family_deltas')
    rows = []
    for dataset in NAMES:
        manifest = datasets[dataset]['manifest']
        for scenario, key in [('B', 'B_K2'), ('B-area', 'B_area_K2'), ('C / C-area', 'C_same')]:
            cohort = manifest['cohorts'][key]
            if scenario == 'C / C-area':
                assert cohort == manifest['cohorts']['C_area_same']
            rows.append(' & '.join([NAMES[dataset], scenario, str(len(cohort)),
                                    ', '.join(cohort) if cohort else 'No eligible category']))
    files['competitor_cohorts.tex'] = table(r'llrp{0.69\textwidth}',
        r'Menu & Study & $n$ & Eligible categories', rows,
        r'\textbf{Exact sampling cohorts.} B requires eight supported '
        r'competitors; C requires two same-family and two cross-family '
        r'competitors. Area controls additionally require per-pair support '
        r'at all three target-area levels. Each cohort is fixed across '
        r'compared variants and fitting seeds. Names retain the saved '
        r'menu capitalization.', 'tab:competitor_cohorts', True)
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    files = render(json.loads(SOURCE.read_text()))
    for name, content in files.items():
        path = ROOT / 'tables' / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f'Out-of-date table: {path}')
        else:
            path.write_text(content)
    print(f'{len(files)} competitor table files ' + ('verified.' if args.check else 'rendered.'))


if __name__ == '__main__':
    main()
