"""Render paper tables from the saved paired-intervention result snapshot.

Run from any directory. --check verifies that the checked-in tables are current.
No model inference or experimental data are modified.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'results/paired_ablation/verified_metrics.json'
LAYERS = (1, 9, 18, 27, 35)
VARIANTS = ('P0', 'P1', 'P2', 'P3', 'random')
NAMES = {
    'P0': 'P0: paired, shared weights',
    'P1': 'P1: single-sided, shared weights',
    'P2': 'P2: raw, shared weights',
    'P3': 'P3: single-sided, own weights',
    'random': 'Random directions (25 sets)',
}
ROW = r' \\' + '\n'
NOTICE = '% Generated by scripts/render_paired_ablation.py; do not edit numbers.\n'


def table(spec, header, rows, caption, label, wide=False):
    env = 'table*' if wide else 'table'
    return (NOTICE + f'\\begin{{{env}}}[t]\n'
            + '    \\centering\n    \\footnotesize\n'
            + '    \\setlength{\\tabcolsep}{4pt}\n'
            + f'    \\begin{{tabular}}{{{spec}}}\n'
            + '        \\toprule\n        ' + header + ROW
            + '        \\midrule\n'
            + ''.join('        ' + row + ROW for row in rows)
            + '        \\bottomrule\n    \\end{tabular}\n'
            + f'    \\caption{{{caption}}}\n    \\label{{{label}}}\n'
            + f'\\end{{{env}}}\n')


def render(data):
    layers = data['layers']
    primary = layers['18']
    for layer in LAYERS:
        result = layers[str(layer)]
        assert result['n_records'] == 2104 and result['n_boot'] == 2000
        for row in result['variants'].values():
            for metric in ('auc', 'ap'):
                assert abs(sum(row[f'per_class_{metric}'].values()) / 10
                           - row[f'macro_{metric}']) < 1e-12
        for comparison, row in result['comparisons'].items():
            lhs, rhs = comparison.split('-')
            delta = (result['variants'][lhs]['macro_auc']
                     - result['variants'][rhs]['macro_auc'])
            assert abs(delta - row['delta_macro_auc']) < 1e-12
            assert row['image_bootstrap_95']['valid_draws'] == 2000
    assert sum(data['endpoint_counts'].values()) == 2 * data['n_records']
    rows = []
    for variant in VARIANTS:
        r = primary['variants'][variant]
        values = [f"{r[key]:.4f}" for key in ('macro_auc', 'macro_ap')]
        if variant == 'P0':
            values = [r'\textbf{' + v + '}' for v in values]
        rows.append(' & '.join([NAMES[variant], *values]))
    files = {'paired_primary.tex': table(
        'lrr', r'Estimator & Macro AUC $\uparrow$ & Macro AP $\uparrow$', rows,
        r'\textbf{Paired-intervention ablation at L18.} Frozen '
        r'Qwen2.5-VL-3B-Instruct; 2,104 fitting records, 10 categories, '
        r'and 5,000 COCO val2017 images. All variants share the same '
        r'cosine/top-5\% readout. AUC and AP use the 0--1 scale. '
        r'The random row averages metrics over 25 direction sets. '
        r'The primary paired AUC difference, P0 minus P1, is '
        r'$+0.0788$ (95\% CI $[+0.0717,+0.0860]$).', 'tab:paired_primary')}
    rows = []
    for layer in LAYERS:
        r = layers[str(layer)]
        vals = [f"{r['variants'][v]['macro_auc']:.4f}" for v in VARIANTS]
        comparison = r['comparisons']['P0-P1']
        delta = 100 * comparison['delta_macro_auc']
        lo, hi = [100 * a for a in comparison['image_bootstrap_95']['interval']]
        rows.append(' & '.join([str(layer), *vals,
                               f'${delta:+.2f}\\;[{lo:+.2f},{hi:+.2f}]$']))
    auc = table('rrrrrrr',
        r'Layer & P0 & P1 & P2 & P3 & Random & P0$-$P1 (pp) [95\% CI]', rows,
        r'\textbf{Macro ROC-AUC across layers.} Settings are identical to '
        r'\cref{tab:paired_primary}. AUCs use the 0--1 scale; paired '
        r'differences and interval endpoints use percentage points (pp). '
        r'L18 is primary. Other layers are secondary and intervals are '
        r'unadjusted for multiple comparisons.', 'tab:paired_layers', wide=True)
    rows = [' & '.join([str(layer)] + [
        f"{layers[str(layer)]['variants'][v]['macro_ap']:.4f}"
        for v in VARIANTS]) for layer in LAYERS]
    ap = table('rrrrrr', 'Layer & P0 & P1 & P2 & P3 & Random', rows,
        r'\textbf{Macro average precision across layers.} Values are point '
        r'estimates on the 0--1 scale. The random control averages AP '
        r'over the same 25 direction sets used for AUC.', 'tab:paired_ap')
    files['paired_layers.tex'] = auc + '\n' + ap
    rows = []
    for name, p0 in primary['variants']['P0']['per_class_auc'].items():
        p1 = primary['variants']['P1']['per_class_auc'][name]
        rows.append(' & '.join([name, str(data['endpoint_counts'][name]),
            str(primary['counts'][name]['positive']), f'{p0:.4f}',
            f'{p1:.4f}', f'${100 * (p0-p1):+.2f}$']))
    files['paired_classes.tex'] = table('lrrrrr',
        r'Category & Fits & Pos. & P0 & P1 & $\Delta$ (pp)', rows,
        r'\textbf{Per-category AUC at L18.} Fits counts records containing '
        r'each category at either endpoint; Pos. counts positive images '
        r'among the 5,000 evaluation images. $\Delta$ is P0 minus P1 '
        r'in percentage points. These are diagnostic point estimates; '
        r'the primary endpoint is macro AUC.', 'tab:paired_classes')
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    files = render(json.loads(SOURCE.read_text()))
    for name, content in files.items():
        target = ROOT / 'tables' / name
        if args.check:
            if not target.exists() or target.read_text() != content:
                raise SystemExit(f'Out-of-date table: {target}')
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
    print(f'{len(files)} ablation table files ' + ('verified.' if args.check else 'rendered.'))


if __name__ == '__main__':
    main()
